### ISSUE TITLE
Metadata version mismatch error in angular 4

### ISSUE THREAD

**Issue by lucifer-AM** [bluehalo/ngx-leaflet#124]
This is the error that I got:-

ERROR in Error: Metadata version mismatch for module project_folder_path/node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts, found version 4, expected 3, resolving symbol LeafletModule in project_folder_path/node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/leaflet.module.d.ts, resolving symbol LeafletModule in project_folder_path/node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/leaflet.module.d.ts
    at syntaxError (project_folder_path\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (project_folder_path\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (project_folder_path\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (project_folder_path\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (project_folder_path\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (project_folder_path\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at project_folder_path\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (project_folder_path\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at project_folder_path\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (project_folder_path\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (project_folder_path\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (project_folder_path\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (project_folder_path\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (project_folder_path\node_modules\@ngtools\webpack\src\plugin.js:495:24)

the solution that I found was that i changed each and every metadata version to the required version.

**Comment by reblace** [comment]
ngx-leaflet 3.x latest is ng5
ngx-leaflet 2.x latest is ng4

Try updating the ngx-leaflet dependency version appropriately and see if it fixes the issue

**Comment by lucifer-AM** [comment]
Thank you so much @reblace. All works fine now.
