### ISSUE TITLE
error TS4029: Public property 'options' of exported class has or is using name 'TileLayer' from external module "..." but cannot be loaded

### ISSUE THREAD

**Issue by steph-del** [bluehalo/ngx-leaflet#174]
Hi,

First of all, thank you for your work !

I'm new to angular. I followed the installation steps to build a basic app from your 'core' example.

Running the app throw this error : 
"error TS4029: Public property 'options' of exported class has or is using name 'TileLayer' from external module "/Users/steph/Documents/Dev/tb-common/tb-geoloc-lib/node_modules/@types/leaflet/index" but cannot be named."

My package.json :
```
"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@types/leaflet": "^1.2.8",
    "core-js": "^2.5.4",
    "@asymmetrik/ngx-leaflet": "^4.x",
    "leaflet": "^1.3.1",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
```

app.module.ts :
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { LeafletModule } from '@asymmetrik/ngx-leaflet';

import { AppComponent } from './app.component';
import { TbGeolocLibModule } from 'tb-geoloc-lib';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    TbGeolocLibModule,
    LeafletModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

my 'map' module :
```
import { NgModule } from '@angular/core';
import { LeafletModule } from '@asymmetrik/ngx-leaflet';

import { TbGeolocLibComponent } from './tb-geoloc-lib.component';
import { MapComponent } from './map/map.component';
import { GeoSearchService } from './_services/geo-search.service';
import { ElevationService } from './_services/elevation.service';

@NgModule({
  imports: [ LeafletModule ],
  declarations: [TbGeolocLibComponent, MapComponent],
  exports: [TbGeolocLibComponent, MapComponent]
})
export class TbGeolocLibModule {
  providers: [
    GeoSearchService, ElevationService
  ];
}
```

and my map component : 
```
import { Component, OnInit } from '@angular/core';
import { latLng, LatLng, tileLayer } from 'leaflet';

@Component({
  selector: 'tb-geoloc-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.css']
})
export class MapComponent implements OnInit {

  options = {
    layers: [
      tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '...' })
    ],
    zoom: 5,
    center: latLng(46.879966, -121.726909)
  };

  constructor() { }

  ngOnInit() {
  }

}
```

In the map component, changing the imports from
`import { latLng, LatLng, tileLayer } from 'leaflet';`
to
`import * as L from 'leaflet';`

and of course `tileLayer -> L.tileLayer`, `latLng -> L.latLng`
Solves the problem but I don't really understand what's going wrong under hood.

Furthermore, related to #77, tree shaking would not work properly.

Thanks.

**Comment by reblace** [comment]
Are you using Angular CLI? If you are, can you see if you can base your project off of this project: https://github.com/Asymmetrik/ngx-leaflet-tutorial-ngcli

**Comment by reblace** [comment]
Also, do you have any custom type definitions? It sounds like there might be a name collision, or a type re-definition or something?

**Comment by Azbesciak** [comment]
I have a similar problem, however - in different scenario. I needed to create shared library which contains customized map component. Before extract, lets say, `map-component` to lib, everything worked fine, but after I have got following problem (log from lib build):

```
BUILD ERROR
projects/map/src/lib/map/map.component.ts(58,3): error TS4029: Public property 'layersControl' of exported class has or is using name 'TileLayer' from external
module "...../node_modules/@types/leaflet/index" but cannot be named.

Error: projects/map/src/lib/map/map.component.ts(58,3): error TS4029: Public property 'layersControl' of exported class has or is using name 'TileLayer' from ex
ternal module "...../node_modules/@types/leaflet/index" but cannot be named.

    at Object.<anonymous> (.....\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at fulfilled (.....\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
    at <anonymous>

projects/map/src/lib/map/map.component.ts(58,3): error TS4029: Public property 'layersControl' of exported class has or is using name 'TileLayer' from external
module "...../node_modules/@types/leaflet/index" but cannot be named.

Error: projects/map/src/lib/map/map.component.ts(58,3): error TS4029: Public property 'layersControl' of exported class has or is using name 'TileLayer' from ex
ternal module "...../node_modules/@types/leaflet/index" but cannot be named.

    at Object.<anonymous> (.....\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at fulfilled (.....\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
    at <anonymous>

```

In my `map-component` I have following imports:
`import {LatLngBounds, rectangle, tileLayer, Map, Marker, Polyline} from 'leaflet';`

after change to 
`import * as L from 'leaflet';`
it works fine but... You know.

Also, when I have added import of `TileLayers` to basic imports (1. version) - it works.

**Comment by reblace** [comment]
If anyone can provide a repo with some basic reproducing code, I can look into this. I've tried to reproduce it myself and have not been able to. Otherwise, I'm going to have to close this as not having enough to go by to try to fix it.

**Comment by reblace** [comment]
Closing due to inability to reproduce.
