### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by gnesher** [bluehalo/ngx-leaflet#194]
I'm unable to run the demo from master (on Windows 10). I saw a similar bug was closed last year and it seems the suggested changes have been implemented - but they don't seem to work on my machine.

This is the error I'm receiving:
```
$ npm run demo

> @asymmetrik/ngx-leaflet@4.0.0 predemo C:\Users\gnesher\work\nortec\ngx-leaflet
> npm run lint


> @asymmetrik/ngx-leaflet@4.0.0 lint C:\Users\gnesher\work\nortec\ngx-leaflet
> tslint -c tslint.json -t stylish 'src/**/*.ts'


> @asymmetrik/ngx-leaflet@4.0.0 demo C:\Users\gnesher\work\nortec\ngx-leaflet
> (webpack-dev-server & npm run watch)

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'webpack-stats-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\gnesher\work\nortec\ngx-leaflet\webpack.conf                                                                                            ig.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

> @asymmetrik/ngx-leaflet@4.0.0 watch C:\Users\gnesher\work\nortec\ngx-leaflet
>  watch 'npm run lint' ./src

> Watching run
> Watching lint'
> Watching ./src
C:\Users\gnesher\work\nortec\ngx-leaflet\node_modules\watch\main.js:73
    if (err) throw err;
             ^

Error: ENOENT: no such file or directory, stat 'C:\Users\gnesher\work\nortec\ngx                                                                                            -leaflet\run'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @asymmetrik/ngx-leaflet@4.0.0 watch: ` watch 'npm run lint' ./src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @asymmetrik/ngx-leaflet@4.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                            ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gnesher\AppData\Roaming\npm-cache\_logs\2018-11-06T17_53_4                                                                                            5_121Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @asymmetrik/ngx-leaflet@4.0.0 demo: `(webpack-dev-server & npm run watc                                                                                            h)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @asymmetrik/ngx-leaflet@4.0.0 demo script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                            ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gnesher\AppData\Roaming\npm-cache\_logs\2018-11-06T17_53_4                                                                                            5_137Z-debug.log
```

**Comment by nick-kolesnikov** [comment]
`webpack-stats-plugin` should be added to dev dependencies.
You can run `npm install --save-dev webpack-stats-plugin` manually.
But after that I've got another error about absence of `rxjs-compat` package. So, you need to install it in the same way as `webpack-stats-plugin` or fix rxjs using in the app.
After that `npm run demo` should works.

**Comment by reblace** [comment]
The latest version fixes this issue and another one related to a bad import from rxjs. Try checking out the latest code on master, which is version 5.x and do a clean `npm install` and then `npm run demo`. Feel free to comment on this if the issue's still there.
