### ISSUE TITLE
Leaflet.JS Library with Angular v15.2.6?

### ISSUE THREAD

**Issue by KHALED-LAKEHAL** [bluehalo/ngx-leaflet#353]
Hello I want use leaflet v1.9.3 with Angular v15.2.6 but I got this exception.

I try many solutions  in the web and use example in official documentation but the problem not resolved yet.

```
TypeError: this._events[type].push is not a function
    at NewClass._on (leaflet-src.js:532:24)
    at NewClass.on (leaflet-src.js:455:12)
    at NewClass.addHooks (leaflet-src.js:13693:22)
    at NewClass.enable (leaflet-src.js:5905:10)
    at NewClass.addHandler (leaflet-src.js:3846:14)
    at NewClass.init (leaflet-src.js:392:14)
    at proto.callInitHooks (leaflet-src.js:359:26)
    at NewClass.initialize (leaflet-src.js:3269:10)
    at new NewClass (leaflet-src.js:302:22)
    at createMap (leaflet-src.js:4863:11)
```

**Comment by reblace** [comment]
Can you provide an example repo of an angular project where you get this error?

**Comment by reblace** [comment]
Closing due to no response.
