### ISSUE TITLE
Angular 18 - Standalone Components - SSR - window is not defined - only imports

### ISSUE THREAD

**Issue by keved93** [bluehalo/ngx-leaflet#369]
I have a Component A (Standalone), in which I import Component B.
Component A does not invoke Component B in its template.
Component B imports the LeafletModule and does nothing else.
Both components only contain **imports without any additional code, checks, or template**s.

Despite **only having the imports**, I constantly receive this error: "window is not defined". I cannot catch or bypass this error since it occurs during the import itself. All previous methods to work around this issue are no longer viable. There must be a mechanism within this module itself that checks if "window" is available or not. If "window" is usable or if the module detects that it is running in a browser and not on a server, then the module should proceed with the initialization.

I do not believe that as developers we can continue to handle this error ourselves in Angular. The provider of the module must intervene and address this issue.

**Comment by reblace** [comment]
In ngx-leaflet, the only reference to the window object is in a HostListener annotation.

Where does the stack trace show the error coming from? Is it in Leaflet.js itself, or ngx-leaflet? If it's coming out of Leaflet.js, I'll have to look into where it's coming from and if we can't prevent that code from getting imported or monkey patch it or something.

**Comment by clcarter** [comment]
In the meantime, this can be rectified by surrounding the component that imports the `LeafletModule` in a `@defer` block. This should ensure it only renders on a client. (tested using standalone components)

**Comment by spiros3p** [comment]
> I have a Component A (Standalone), in which I import Component B. Component A does not invoke Component B in its template. Component B imports the LeafletModule and does nothing else. Both components only contain **imports without any additional code, checks, or template**s.
> 
> Despite **only having the imports**, I constantly receive this error: "window is not defined". I cannot catch or bypass this error since it occurs during the import itself. All previous methods to work around this issue are no longer viable. There must be a mechanism within this module itself that checks if "window" is available or not. If "window" is usable or if the module detects that it is running in a browser and not on a server, then the module should proceed with the initialization.
> 
> I do not believe that as developers we can continue to handle this error ourselves in Angular. The provider of the module must intervene and address this issue.

Hi @keved93 , here is what worked for me:
- lazy load the component A in the route
- in the file app.routes.server.ts, set the particular path for the component A to render in the client

**Comment by blazekv** [comment]
> In the meantime, this can be rectified by surrounding the component that imports the `LeafletModule` in a `@defer` block. This should ensure it only renders on a client. (tested using standalone components)

This is true only if you dont have **incremental hydration**. Defer block is rendered on server side if incremental hydration is enabled - see https://angular.dev/guide/incremental-hydration#how-does-incremental-hydration-work

**Comment by GipHub123** [comment]
I also had problems with SSR and I was able to pin point error to ` node_modules/leaflet/dist/leaflet-src.js`
Error occured when i tried to access any of the pages, for example lazy loaded route with with zero logic / imports.

```

Error: window access on server
    at get (C:\angular\project\src\main.server.ts:8:19)
    at eval (C:\angular\project\.cache\20.2.0\app\vite\deps_ssr\chunk-OWWCKS3R.js:138:23)
    at eval (C:\angular\project\.cache\20.2.0\app\vite\deps_ssr\chunk-OWWCKS3R.js:10:70)
    at node_modules/leaflet/dist/leaflet-src.js (C:\angular\project\.cache\20.2.0\app\vite\deps_ssr\chunk-OWWCKS3R.js:11:7)
    at __require2 (C:\angular\project\.cache\20.2.0\app\vite\deps_ssr\chunk-VIB2VHHA.js:45:50)
    at eval (C:\angular\project\.cache\20.2.0\app\vite\deps_ssr\@bluehalo_ngx-leaflet.js:35:49)
    at async ESModulesEvaluator.runInlinedModule (file:///C:/angular/project/node_modules/vite/dist/node/module-runner.js:910:3)
    at async SSRCompatModuleRunner.directRequest (file:///C:/angular/project/node_modules/vite/dist/node/module-runner.js:1119:59)
    at async SSRCompatModuleRunner.directRequest (file:///C:/angular/project/node_modules/vite/dist/node/chunks/dep-CMEinpL-.js:18901:22)
    at async SSRCompatModuleRunner.cachedRequest (file:///C:/angular/project/node_modules/vite/dist/node/module-runner.js:1037:73)


  Error: Error(s) occurred while extracting routes:
- Error in handleRoute for '/data/:id/basic': Cannot read properties of undefined (reading 'requestAnimationFrame')
- Error in handleRoute for '/data/:id/connections': Cannot read properties of undefined (reading 'requestAnimationFrame')
```

```
      var emptyImageUrl = "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=";
      function getPrefixed(name) {
        return window["webkit" + name] || window["moz" + name] || window["ms" + name];
      }
      var lastTime = 0;
      function timeoutDefer(fn) {
        var time = +/* @__PURE__ */ new Date(), timeToCall = Math.max(0, 16 - (time - lastTime));
        lastTime = time + timeToCall;
        return window.setTimeout(fn, timeToCall);
      }
      var requestFn = window.requestAnimationFrame || getPrefixed("RequestAnimationFrame") || timeoutDefer;
      var cancelFn = window.cancelAnimationFrame || getPrefixed("CancelAnimationFrame") || getPrefixed("CancelRequestAnimationFrame") || function(id) {
        window.clearTimeout(id);
      };
```

```
@Component({
  selector: 'rt-chart-analysis-segmentation-region',
  templateUrl: './chart-analysis-segmentation-region.component.html',
  styleUrls: [
    './chart-analysis-segmentation-region.component.scss'
  ],
  imports: [
    LeafletModule,
    FormsModule
  ]
})

```
This component is under  `@feature/chart/component/index`. Some lazy loaded routes / views import this `@feature/chart/component/index`.

**Comment by reblace** [comment]
Thanks for the detailed report, and to everyone who chimed in on this. Let me give a thorough explanation of what's actually happening here and where things stand.

## Root cause

The error originates in **Leaflet itself**, not in ngx-leaflet. Specifically, `leaflet/src/core/Browser.js` executes browser detection code at the **top level of the module** — not inside functions, not lazily, but immediately when the module is first imported:

```javascript
var style = document.documentElement.style;
var ie = 'ActiveXObject' in window;
var webkit3d = ('WebKitCSSMatrix' in window) && ...
var retina = (window.devicePixelRatio || ...) > 1;
// many more...
```

The moment `import 'leaflet'` is evaluated on the server, Node.js hits these lines and throws `window is not defined`. This happens at module initialization time — before any Angular component, directive, or service code runs.

## Why ngx-leaflet can't fix this

Angular's SSR tools (`isPlatformBrowser`, `PLATFORM_ID`, `inject(PLATFORM_ID)`) are **runtime guards**. They work inside components and services after Angular's infrastructure is running. They cannot prevent a static `import 'leaflet'` from executing Leaflet's module initialization code on the server.

ngx-leaflet's own code has only one reference to `window` — a `@HostListener('window:resize')` in `LeafletDirective` — which only registers a listener when the directive is instantiated and would never run on the server anyway. That's not the source of the problem.

## What about existing solutions?

Two libraries have been referenced in related discussions as having solved this:

- **react-leaflet-universal** — doesn't actually solve it. It renders `null` on the server by relying on `componentDidMount` never running during SSR. No map output server-side, and it's pinned to React Leaflet 2.x (obsolete).
- **leaflet-map-server-component** — a more ambitious approach that sandboxes Leaflet's source inside a function and injects a Domino fake-DOM as `window`/`document`. Closer to a real fix, but it only works with Leaflet **0.7.7**, is abandoned, and breaks with Leaflet 1.x because Leaflet now accesses `window` at module evaluation scope rather than inside a function scope.

Neither is a viable path forward for Leaflet 1.x.

## Working workarounds today

**1. Mark the route as client-only (most reliable)**

In `app.routes.server.ts`, set the route containing your map to render client-side only:
```typescript
import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  { path: 'your-map-route', renderMode: RenderMode.Client },
  { path: '**', renderMode: RenderMode.Prerender }
];
```
This is explicit, supported, and works with all Angular SSR configurations including incremental hydration.

**2. `@defer` block (with caveats)**

Wrapping the component in a `@defer` block works in most cases:
```html
@defer (on browser) {
  <your-map-component />
}
```
However, as noted in this thread, this breaks if **incremental hydration** is enabled, since Angular will attempt to render deferred blocks on the server in that mode.

**3. Lazy-loaded route**

As noted in the comments, lazy-loading Component A via the router and configuring its path to render client-side in `app.routes.server.ts` achieves the same result as option 1.

## The path to a real fix

Proper SSR support for Leaflet requires Leaflet itself to guard its browser detection code with `typeof window !== 'undefined'` checks, the same way modern SSR-compatible libraries do. This is something the Leaflet core team would need to address — ideally in **Leaflet 2.0**, which is currently in development. We're tracking that in #380. Once Leaflet 2.0 is released, we'll evaluate what's needed to properly support SSR in ngx-leaflet.

In the meantime, option 1 (`RenderMode.Client`) is the cleanest workaround — it's honest about the fact that a map is an inherently interactive, browser-only experience, and lets the rest of your app SSR normally.

**Comment by reblace** [comment]
Closing this since pinned issues remain visible even if they are closed (I hope!).
